### ISSUE TITLE
What to do after main is called?

### ISSUE THREAD

**Issue by maxdd** [competencytestlvl/webdriver_auto_update#13]
I'm failing to comprehend out to pass to selenium the driver.
In the past i was doing:

```
check_driver(os.path.dirname(os.path.abspath(__file__)) + "\\driver\\")
driver = webdriver.Chrome(options=options)
```

but now

```
Local chromedriver version: 117.0.5938.149
Latest online chromedriver version: 117.0.5938.149

DevTools listening on ws://127.0.0.1:52863/devtools/browser/84819afd-14d3-4bbc-8226-24fb6a89ff89
Traceback (most recent call last):
  File "****\main.py", line 17, in <module>
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "****Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 49, in __init__
    super().__init__(
  File "****Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "****Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "****Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "****Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "****Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 117.0.5938.134 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
```

as if it is using something else

i've tried adding
```
options.binary_location = driver_directory
```
but i get 
```
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create Chrome process.
```

**Comment by maxdd** [comment]
had to use

```
from selenium.webdriver.chrome.service import Service
service = Service(executable_path=driver_directory + "\\chromedriver.exe")
```
